using System.Text.Json.Serialization;
using Bzn.Cloudios.Domain.Dto;

namespace Bzn.Cloudios.WebAPI.Serialization;

[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(UserInfo))]
[JsonSerializable(typeof(RealmListResponse))]
[JsonSerializable(typeof(RealmItem))]
[JsonSerializable(typeof(RealmDetailResponse))]
[JsonSerializable(typeof(RealmUserItem))]
[JsonSerializable(typeof(CreateRealmRequest))]
[JsonSerializable(typeof(UpdateRealmRequest))]
[JsonSerializable(typeof(UserListResponse))]
[JsonSerializable(typeof(UserItem))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(ContainerListResponse))]
[JsonSerializable(typeof(ContainerListItem))]
[JsonSerializable(typeof(ContainerDetailResponse))]
[JsonSerializable(typeof(CreateContainerRequest))]
[JsonSerializable(typeof(ContainerActionResponse))]
[JsonSerializable(typeof(ContainerVolumeDto))]
[JsonSerializable(typeof(ContainerVolumeRequest))]
[JsonSerializable(typeof(List<ContainerVolumeRequest>))]
[JsonSerializable(typeof(ContainerEnvVarDto))]
[JsonSerializable(typeof(ContainerLogsResponse))]
[JsonSerializable(typeof(ContainerLogEntry))]
[JsonSerializable(typeof(AdminContainerListResponse))]
[JsonSerializable(typeof(AdminContainerListItem))]
[JsonSerializable(typeof(ContainerMetricsResponse))]
[JsonSerializable(typeof(MetricDataPoint))]
[JsonSerializable(typeof(HostMetricsResponse))]
[JsonSerializable(typeof(RealmBillingResponse))]
[JsonSerializable(typeof(BillingServiceItem))]
[JsonSerializable(typeof(GlobalBillingResponse))]
[JsonSerializable(typeof(RealmBillingItem))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ErrorResponse))]
public sealed partial class CloudiosJsonSerializerContext : JsonSerializerContext;
