// <auto-generated />
using System;
using Bzn.Cloudios.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bzn.Cloudios.Infrastructure.Migrations
{
    [DbContext(typeof(CloudiosDbContext))]
    [Migration("20260617133435_AddManagedAppTemplateInternalPort")]
    partial class AddManagedAppTemplateInternalPort
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.BillingPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostBRL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0m);

                    b.Property<double>("Hours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<Guid?>("ManagedDatabaseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ContainerId", "StartedAtUtc");

                    b.HasIndex("ManagedDatabaseId", "StartedAtUtc");

                    b.ToTable("BillingPeriods", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPerHourBRL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.02m);

                    b.Property<double>("CpuLimitCores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerContainerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HostPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InternalPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(8080);

                    b.Property<long>("MemoryLimitBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(536870912L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Stopped");

                    b.HasKey("Id");

                    b.HasIndex("DockerContainerId");

                    b.HasIndex("Name");

                    b.HasIndex("RealmId");

                    b.HasIndex("RealmId", "Status");

                    b.ToTable("Containers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Containers_Status", "Status IN ('Deploying','Running','Stopped','Failed')");
                        });
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerEnvVar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("ContainerId", "Key")
                        .IsUnique();

                    b.ToTable("ContainerEnvVars", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerVolume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("ContainerVolumes", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.DatabaseTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuLimitCores")
                        .HasColumnType("REAL");

                    b.Property<long>("MemoryLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseTiers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            CpuLimitCores = 0.5,
                            MemoryLimitBytes = 524288000L,
                            Name = "dbl-micro-1s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            CpuLimitCores = 0.5,
                            MemoryLimitBytes = 1073741824L,
                            Name = "dbl-micro-2s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            CpuLimitCores = 1.0,
                            MemoryLimitBytes = 1073741824L,
                            Name = "dbl-mini-1s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            CpuLimitCores = 2.0,
                            MemoryLimitBytes = 1073741824L,
                            Name = "dbl-mini-2s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            CpuLimitCores = 2.0,
                            MemoryLimitBytes = 2147483648L,
                            Name = "dbl-standard-1s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            CpuLimitCores = 2.0,
                            MemoryLimitBytes = 4294967296L,
                            Name = "dbl-standard-2s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            CpuLimitCores = 4.0,
                            MemoryLimitBytes = 4294967296L,
                            Name = "dbl-standard-3s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            CpuLimitCores = 4.0,
                            MemoryLimitBytes = 8589934592L,
                            Name = "dbl-large-1s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            CpuLimitCores = 8.0,
                            MemoryLimitBytes = 10737418240L,
                            Name = "dbl-large-2s"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000110"),
                            CpuLimitCores = 10.0,
                            MemoryLimitBytes = 12884901888L,
                            Name = "dbl-large-3s"
                        });
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ManagedAppInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPerHourBRL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.02m);

                    b.Property<double>("CpuLimitCores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerContainerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostPort")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryLimitBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(536870912L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Micro1s");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Provisioning");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockerContainerId");

                    b.HasIndex("HostPort")
                        .IsUnique();

                    b.HasIndex("RealmId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("RealmId", "Name")
                        .IsUnique();

                    b.ToTable("ManagedAppInstances", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagedAppInstances_Status", "Status IN ('Provisioning','Running','Stopped','Failed','Terminated')");
                        });
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ManagedAppTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultEnvVars")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultInstanceSize")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Micro1s");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InternalPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(80);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ManagedAppTemplates", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ManagedDatabaseInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuLimit")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("MemoryLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Provisioning");

                    b.Property<Guid>("TierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RealmId");

                    b.HasIndex("TierId");

                    b.HasIndex("RealmId", "Name")
                        .IsUnique();

                    b.HasIndex("RealmId", "Status");

                    b.ToTable("ManagedDatabaseInstances", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagedDatabaseInstances_Status", "Status IN ('Provisioning','Running','Stopped','Failed')");

                            t.HasCheckConstraint("CK_ManagedDatabaseInstances_Type", "Type IN ('MySQL','MongoDB')");
                        });
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Realm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Realms", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RealmId");

                    b.HasIndex("RealmId", "Role");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "Role IN ('PlatformAdmin','PlatformUser','PlatformSre','RealmOwner','RealmAdmin','RealmUser','RealmSre')");
                        });
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Container", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Realm", "Realm")
                        .WithMany("Containers")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerEnvVar", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Container", "Container")
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerVolume", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Container", "Container")
                        .WithMany("Volumes")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ManagedAppInstance", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bzn.Cloudios.Domain.Entities.ManagedAppTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Realm");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ManagedDatabaseInstance", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Realm", "Realm")
                        .WithMany("ManagedDatabases")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bzn.Cloudios.Domain.Entities.DatabaseTier", "Tier")
                        .WithMany("Instances")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Realm");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.User", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Realm", "Realm")
                        .WithMany("Users")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Container", b =>
                {
                    b.Navigation("EnvironmentVariables");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.DatabaseTier", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Realm", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("ManagedDatabases");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
