// <auto-generated />
using System;
using Bzn.Cloudios.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bzn.Cloudios.Infrastructure.Migrations
{
    [DbContext(typeof(CloudiosDbContext))]
    [Migration("20260601232640_FixDependencyInjection")]
    partial class FixDependencyInjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.BillingPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostBRL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0m);

                    b.Property<double>("Hours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ContainerId", "StartedAtUtc");

                    b.ToTable("BillingPeriods", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPerHourBRL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.02m);

                    b.Property<double>("CpuLimitCores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InternalPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(8080);

                    b.Property<long>("MemoryLimitBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(536870912L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Stopped");

                    b.HasKey("Id");

                    b.HasIndex("DockerContainerId");

                    b.HasIndex("Name");

                    b.HasIndex("RealmId");

                    b.HasIndex("RealmId", "Status");

                    b.ToTable("Containers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Containers_Status", "Status IN ('Deploying','Running','Stopped','Failed')");
                        });
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerEnvVar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("ContainerId", "Key")
                        .IsUnique();

                    b.ToTable("ContainerEnvVars", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerVolume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("ContainerVolumes", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Realm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Realms", (string)null);
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RealmId");

                    b.HasIndex("RealmId", "Role");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "Role IN ('PlatformAdmin','PlatformUser','PlatformSre','RealmOwner','RealmAdmin','RealmUser','RealmSre')");
                        });
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Container", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Realm", "Realm")
                        .WithMany("Containers")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerEnvVar", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Container", "Container")
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.ContainerVolume", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Container", "Container")
                        .WithMany("Volumes")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.User", b =>
                {
                    b.HasOne("Bzn.Cloudios.Domain.Entities.Realm", "Realm")
                        .WithMany("Users")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Container", b =>
                {
                    b.Navigation("EnvironmentVariables");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Bzn.Cloudios.Domain.Entities.Realm", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
